### ISSUE TITLE
Nano 33 BLE Sense Rev2 - 802.15.4 / Zigbee - Nordic SDK

### ISSUE THREAD

**Issue by qrpyr** [arduino/ArduinoCore-mbed#1003]
Aside Bluetooth LE and NFC, the NINA B306 also supports IEEE 802.15.4 radio mode via its integrated Nordic nRF52840 chipset. 802.15.4 is used for the Zigbee protocoll for instance, which I try to use. Zigbee capability is also mentioned in the PDF Docs of the Nano 33 BLE Sense Rev2, but it seems that it is not officially supported.

A Nordic SDK is included in the code, but 802.15.4 / Zigbee requires an additional Nordic SDK as I understand, or their newer nRF Connect SDK.

Is there any ongoing effort to include Zigbee support for the Sense Rev2?
What are the steps theoretically required to undergo for adding Zigbee support?

**Comment by facchinm** [comment]
Hi @qrpyr ,
for all new developments on Nano33BLE we are targeting [Zephyr](https://github.com/arduino/ArduinoCore-zephyr) . Adding support for Zigbee should be "easy" after following this guide: https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/protocols/zigbee/configuring.html#ug-zigbee-configuring .
In this very moment we are focusing on porting the core functionalities, but in the long run this kind of support will be easier to add
