### ISSUE TITLE
Define CORE_CM4 deprecated

### ISSUE THREAD

**Issue by hpssjellis** [arduino/ArduinoCore-mbed#102]
See link  [here](https://github.com/arduino/ArduinoCore-mbed/blob/eebf730890cca2422a849150256745598dbf34f5/libraries/ThreadDebug/src/ThreadDebug.h#L37)

Hasn't the use of CORE_CM4 been deprecated, and replaced with 

[PORTENTA_H7_M4](https://github.com/arduino/ArduinoCore-mbed/blob/eebf730890cca2422a849150256745598dbf34f5/variants/PORTENTA_H7_M4/defines.txt#L68)

**Comment by facchinm** [comment]
`PORTENTA_H7_M4` is more specific to recognize the target, but it' not generic (it will only be applied to Portenta boards of course).
For a cross compatibility with all STM32H747 boards, the linked snippet from ThreadDebug works better. `CORE_CM4` is still defined here https://github.com/arduino/ArduinoCore-mbed/blob/eebf730890cca2422a849150256745598dbf34f5/variants/PORTENTA_H7_M4/defines.txt#L10 :wink:
