### ISSUE TITLE
Only one SPI on the Portenta board ?

### ISSUE THREAD

**Issue by semir-tursunovic** [arduino/ArduinoCore-mbed#115]
Is it possible that the SPI driver for the Portenta board enables us to control only SPI1 ?

STM32H747 has 6 SPI peripherals but as far as I can see you only have driver for the SPI1. Following the analogy from the previous version of the Arduino platform I tried to use other SPI peripherals but with no luck. 

How can we use the other SPI peripherals ?

**Comment by facchinm** [comment]
Hi @semir-tursunovic ,
we are only exposing one right now but as you correctly noted there are a lot.
In the sketch you can declare
```
arduino::MbedSPI mySPI(SPI_MISO, SPI_MOSI, SPI_SCK);
```
with `SPI_x` replaced with actual pins (like `PC_6`).
We'll be adding all possibile muxes as soon as the breakout carrier is avaliable.
