### ISSUE TITLE
WifiUdp.parsePacket() blocking

### ISSUE THREAD

**Issue by MosiMiso** [arduino/ArduinoCore-mbed#123]
Hi all!

When using WifiUdp on portenta H7 i recognized a different behaviour compared to Arduino MKR1010
Now WiFiUDP.parsePacket() is blocking for 1s if no message is available.
Looking into WifiUDP.h i recognized a hardcoded timeout of 1000ms.

My suggestion:
- make the timeout  user settable
- make the socket non blocking (or let the user decide by offering a setter)

_socket.set_blocking(false); 
in WiFiUDP.begin(uint16_t port)

Best regards
Michael

**Comment by facchinm** [comment]
Should be fixed by https://github.com/arduino/ArduinoCore-mbed/pull/281

**Comment by facchinm** [comment]
Closing as fixed since #281 was merged
