### ISSUE TITLE
analogReference() not implemented for Portenta H7

### ISSUE THREAD

**Issue by sebromero** [arduino/ArduinoCore-mbed#161]
Using `analogReference()` in a sketch throws a linker error. Looking at the code, there seems to be only an implementation for the Nano33 BLE variant but not for the H7.

**Comment by sebromero** [comment]
@facchinm ☝️

**Comment by malmr** [comment]
Unfortunately still not working

**Comment by facchinm** [comment]
To set the analog reference in STM32H7 boards there's no need to call any function, just connect the external reference to AREF pin and it will be used. I'm going to add an empty function with a warning at compile time to make the linker happy.

**Comment by romainreignier** [comment]
It would be nice to be able to use the `INTERNAL` reference voltage of the stm32 to be able to do some analog readings without needing an external reference. The built-in pull-up on the AREF pin provides analog values that are not stable as stated several times in the forum.

**Comment by sebromero** [comment]
@romainreignier As far as I know, an external voltage reference is required for stable readings. When not connecting it, it automatically uses the internal voltage reference via weak pull-ups. Correct me if I'm wrong @facchinm
