### ISSUE TITLE
Portenta Tutorial - MBED v. 1.9.5?

### ISSUE THREAD

**Issue by jwestmoreland** [arduino/ArduinoCore-mbed#17]
Hello,

Please see the attached pic - I only see version 1.2.1 - not 1.9.5 - I'm assuming this was a pre-beta release - but wanted to point it out since it can be a source of confusion when going through the tutorials.

Regards,
John W.
![boardsmanager1p9p5](https://user-images.githubusercontent.com/2308903/87366027-8c38ff80-c52c-11ea-9ce1-db71b09d795b.jpg)

**Comment by facchinm** [comment]
@sbhklr can you check this and create new screenshots?
@jwestmoreland you are right, it was a prerelease.

**Comment by sbhklr** [comment]
> @sbhklr can you check this and create new screenshots?
> @jwestmoreland you are right, it was a prerelease.
@facchinm for sure. Can you please assign the GH issue to me?

**Comment by sbhklr** [comment]
@facchinm Done. You may close the issue.

**Comment by jwestmoreland** [comment]
Thanks Sebastian and Martino!
