### ISSUE TITLE
STM32LO LoRa Murata Module I2C Communication with PortentaH7 M7 core

### ISSUE THREAD

**Issue by hpssjellis** [arduino/ArduinoCore-mbed#211]
Does anyone know if the STM32LO Module I2C  pins ```PB_9``` SDA,  ```PB_8``` SCL are able to be used?

Using this pdf on page 7  [https://content.arduino.cc/assets/SL-ASX00026.PDF](https://content.arduino.cc/assets/SL-ASX00026.PDF)

![image](https://user-images.githubusercontent.com/5605614/116497912-510a8180-a85d-11eb-8126-89f36291622a.png)

Looks easy enough to communicate with the STM32LO  Murata module , I can load simple Slave or Master wire.h programs onto it, but when I try to read it using the PortentaH7 M7 core also running wire.h slave or master I get nothing. Any suggestions?

P.S. Communicating with the STM32LO Lora module is a bit complex @facchinm has a method [here](https://github.com/arduino-libraries/MKRWAN/issues/87#issuecomment-826180994)

Also does anyone know if SPI is working?

**Comment by facchinm** [comment]
Hi Jeremy,
if you look at the top page, only the UART and a couple of control GPIOs are actually routed 
![image](https://user-images.githubusercontent.com/8843437/116516760-4805c880-a8ce-11eb-9869-7e6a6d3464f4.png)
So, no way to communicate via other means :neutral_face:

**Comment by hpssjellis** [comment]
Thanks @facchinm that explains why I can only communicate from the Portenta  M7 Core to the Murata LoRa Module  using: 

```
UART mySerial3(PJ_8,  PJ_9,  NC, NC); //TX, TR, RTS, CTS  NOTE: NC means not connected

```


It works fine, so I should be good.
