### ISSUE TITLE
adding more RP2040 board support

### ISSUE THREAD

**Issue by ladyada** [arduino/ArduinoCore-mbed#216]
hi folks, adafruit has designed a few RP2040-based boards that we'd like to have a board-support-package have a variant for

will arduino be merging PR's that add support for 3rd party boards?

**Comment by alranel** [comment]
Sure thing!
You'll need to open one PR on the https://github.com/arduino/mbed-os repository and a PR on this one.
(Hint: as an alternative to providing a dedicated variant for your boards you can also consider the option to reference the `RASPBERRY_PI_PICO` variant, if there are no special needs. This way you only need to add the entry to [boards.txt](RASPBERRY_PI_PICO))

**Comment by ladyada** [comment]
awesome thank you @alranel!
