### ISSUE TITLE
Get message "Please run as root" when installing or updating Pico/Nano/Portenta boards

### ISSUE THREAD

**Issue by Gerriko** [arduino/ArduinoCore-mbed#231]
I'm using Linux Mint 19 (Ubuntu 18.04) and I've the latest Arduino IDE 1.8.15 installed.

I can install/update all other boards using Boards Manager... without issue or notification but when I'm installing/updating the  Pico/Nano/Portenta (Mbed) boards using Boards Manager I get this message in the terminal window/console of the IDE saying "Please run as root".

Despite the message, everything seems in order.

Just curious if it's something on my end.

**Comment by josefwegner** [comment]
The post_install.sh script that adds an udev rule for the RP2040 bootloader failed.
You can run it manually with:
`sudo $HOME/.arduino15/packages/arduino/hardware/mbed_nano/2.1.0/post_install.sh` (Nano)
`sudo $HOME/.arduino15/packages/arduino/hardware/mbed_rp2040/2.1.0/post_install.sh` (Pico)

I do not have the Protenta support installed, but you should find the post_install.sh for it somewhere in $HOME/.arduino15/packages/arduino/hardware.
