### ISSUE TITLE
Nano RP2040 Connect on Linux Machine

### ISSUE THREAD

**Issue by kd8bxp** [arduino/ArduinoCore-mbed#236]
Problem: Compiled sketches failed to up load to board. 
Version: Linux Mint 20.1 (probably all versions of linux)
Arduino IDE: 1.8.13 
Core: Arduino Mbed OS Nano Boards v2.1.0

My Solution install a udev rule into ```etc/udev/rules.d```

My rule:
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d6b", MODE:="0666"
```
There is probably other/better rules for the board, but this worked for me.

**Comment by facchinm** [comment]
https://github.com/arduino/ArduinoCore-mbed/blob/master/post_install.sh should be executed by the IDE but of course it must be run as superuser; I think the documentation already contains this info but, if not, we clearly need to add int. @per1234 @arduino/ft_content
