### ISSUE TITLE
SPI default clock rate on RP2040 boards is slower than Arduino API Standard.

### ISSUE THREAD

**Issue by WestfW** [arduino/ArduinoCore-mbed#245]
The RP2040 implementation of SPI has (in the relevant SPI.h):
```
class MbedSPI : public SPIClass
{
   :
private:
    SPISettings settings = SPISettings(0, MSBFIRST, SPI_MODE0);
   : 
```
where "0" is the bitrate.   Presumably, at some point this is converted to the default SPI clock rate for mBed, buried deep inside the mBed code, and it becomes about 1MHz.   However, I think it should be just:
```
    SPISettings settings = SPISettings();
```
or perhaps
```
   SPISettings = DEFAULT_SPI_SETTINGS;
```
(both of which come from API/HardwareSPI.h, and defined a default bitrate of 4MHz.)

With the current code, the default SPI bitrate for RP2040 based boards is one quarter of the speed that it is on an AVR.

A possible workaround, and to get higher speeds, is for uses to provide their own SPI settings:
```
SPISettings mySPIsettings = SPISettings(10000000, MSBFIRST, SPI_MODE0);  //10MHz
SPI.beginTransaction(mySPIsettings);
```

**Comment by facchinm** [comment]
Hi Bill,
the code is indeed buried but here https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/SPI/SPI.cpp#L79 and here https://github.com/arduino/ArduinoCore-API/blob/master/api/HardwareSPI.h#L55-L66 . The initial clock as 0 means that the first beginTransaction() will indeed configure the SPI peripheral to the given `SPISettings`.
The clock at 1Mhz instead then 4Mhz might be an issue in the porting layer, I'm checking with a scope and will report back soon.

**Comment by facchinm** [comment]
Just checked with a scope and with the following code I get correctly a 4Mhz clock
```c++
#include "SPI.h"

void setup() {
  // put your setup code here, to run once:
  SPI.begin();
}

void loop() {
  // put your main code here, to run repeatedly:
  SPI.beginTransaction(DEFAULT_SPI_SETTINGS);
  for (int i = 0; i < 100; i++) {
    SPI.transfer(i);
  }
  SPI.endTransaction();
  delay(1000);
}
```
Closing the issue for the moment, if there's anything else I didn't take into account please let me know :wink:
