### ISSUE TITLE
CRC doesn't match

### ISSUE THREAD

**Issue by KJCornett19** [arduino/ArduinoCore-mbed#249]
I'm trying to download the necessary board manager files (Ardunio Mbed Nano Boards) for the Nano 33 BLE board but I'm getting the error "CRC doesn't match, files is corrupted. It may be a temporary problem, please retry later." 

Windows 10 Enterprise

How can I resolve this issue?

**Comment by facchinm** [comment]
Hi @KJCornett19 ,
which version of the IDE are you using? On recent versions you can try installing the core again and the file will be redownloaded. If you always get the same error it might be a firewall/networking issue.
