### ISSUE TITLE
nano 33 ble for nRF52833

### ISSUE THREAD

**Issue by UGMWJ** [arduino/ArduinoCore-mbed#273]
Hi,

I have build my custom design based on nano 33 ble but couldn't fabricate the design as  NINA-B306-00B is out of stock. I thought to use NINA-B400-00B if it is possible to compile Arduino library for nRF52833 mcu instead of current nRF52840 mcu. 

Please let me know how I can compile nano 33 BLE for new MCU - nRF52833.

Many thanks and kind regards,
Ghalib

**Comment by facchinm** [comment]
Hi @UGMWJ ,
from [this table](https://www.nordicsemi.com/-/media/Publications/WQ-Product-guide/Wireless-Q---Q1---Product-Guide.pdf?la=en&hash=55195302B5331ECA0F7D841B58D7F97DCC945F26) it looks like nRF52833 and nRF52840 have the same peripheral set except QSPI and Cryptocell.  nRF52833 is not yet supported on mbed-os but I think the nRF52840 (nano33ble) build should work to a certain extent.

When it will be supported, you'll be able to compile `libmbed` for your target by running
```./mbed-os-to-arduino $TARGET_NAME:$VARIANT_NAME``` and then creating the relevant entries in `boards.txt`.

Let me know if it works when setting Nano 33 BLE as target; I'm closing the issue in the meantime.

**Comment by alvee1994** [comment]
hi @UGMWJ ,

Wow I am in the same position now. did you get your device to work?

**Comment by ghalibjanjua** [comment]
Hi @alvee1994 

I did tired it as I was able to get NINA-B306-00 boards. Best of luck for your work.

**Comment by ghalibjanjua** [comment]
Many thanks @facchinm 

G
