### ISSUE TITLE
Which is the latest version?

### ISSUE THREAD

**Issue by fabianoriccardi** [arduino/ArduinoCore-mbed#275]
I was looking for the latest version of this Core, but the latest version seems to be 2.1.0, while the 2.2.0 (regularly installed trough arduino) is just a git tag. Is it an oversight?

![Screenshot 2021-07-04 230732](https://user-images.githubusercontent.com/7937648/124399618-d3f7fe80-dd1c-11eb-8265-b520df089ddd.png)

**Comment by facchinm** [comment]
Hi @fabianoriccardi ,
the tag is indeed a release, so 2.2.0 is the latest. I'm going to create proper release with the changelog as soon as I have a bit of time :slightly_smiling_face:
