### ISSUE TITLE
Flash size of Nano RP2040 Connect wrong?

### ISSUE THREAD

**Issue by maxgerhardt** [arduino/ArduinoCore-mbed#285]
Per

https://github.com/arduino/ArduinoCore-mbed/blob/52f7f1583b29bb35811ab71b9b2fd3498b7eed99/variants/NANO_RP2040_CONNECT/linker_script.ld#L1-L7

this board has 2MByte flash. but if I look at Earle Philhower's core [here](https://github.com/earlephilhower/arduino-pico/blob/47a4d9f8033c6d96c858a3ed9ada46391f7c8bbf/boards.txt#L3002-L3004)

```ini
arduino_nano_connect.menu.flash.16777216_0=16MB (no FS)
arduino_nano_connect.menu.flash.16777216_0.upload.maximum_size=16773120
arduino_nano_connect.menu.flash.16777216_0.build.flash_length=16773120
```
it has 16 MByte of flash. Same as [the product page](https://store.arduino.cc/nano-rp2040-connect) says.

>Memory | AT25SF128A-MHB-T | 16MB Flash IC

Is the linker script just wrong or is there a technical limitation with the sketch size being limited to 2MB?

**Comment by facchinm** [comment]
Should be fixed by https://github.com/arduino/ArduinoCore-mbed/blob/master/patches/0084-Nano-RP2040-Connect-force-flash-size-to-16MB.patch which was merged as https://github.com/arduino/ArduinoCore-mbed/commit/a09bee8418012267fde2d8f0bbd90fa7570a23ed and will be part of the upcoming core release
