### ISSUE TITLE
.\Arduino15\packages\arduino\tools\openocd\0.10.0-arduino13\bin\openocd.exe - Goes To Zero Bytes During Programming

### ISSUE THREAD

**Issue by jwestmoreland** [arduino/ArduinoCore-mbed#29]
I'm not 100% certain how to reproduce this - but I will try in the near future but want to report what happened:

I was trying to restore the bootloader on the Portenta H7 - when all of a sudden I got a message:

'File cannot be run by this PC' - or a similar message.  I didn't do a screen shot since at first I thought it was just a path issue or something like that - I finally looked in the directory:

C:\Users\john\AppData\Local\Arduino15\packages\arduino\tools\openocd\0.10.0-arduino13\bin -
and the openocd.exe file was there - but was zero bytes.

I since have restored it and I put the read-execute only flag on it so it can't be deleted or written to as easily - but I wanted to report this just in case this isn't some kind of one-off and someone else is seeing it. 

Regards,
John W.

**Comment by facchinm** [comment]
Closing since it looked like a one-off event :slightly_smiling_face:
