### ISSUE TITLE
No LED_BUILTIN defined for EDGE_CONTROL

### ISSUE THREAD

**Issue by aentinger** [arduino/ArduinoCore-mbed#295]
Does the board not have a `LED_BUILTIN`? Strikes me as strange as it would be the first Arduino board to be without builtin LED.

**Comment by manchoz** [comment]
No, it doesn't.

The only LED is connected to an I/O expander that requires an external library to be operated.

**Comment by aentinger** [comment]
It's a pity because it tripped CI on one of my libraries and rather needs a complicated fix. But you are right, there's no LED connected to any GPIO directly :(
