### ISSUE TITLE
RPI PICO flash storage

### ISSUE THREAD

**Issue by pangflash** [arduino/ArduinoCore-mbed#297]
I don't know how to implement the flash storage of RPI Pico. Is there a manual on this?

**Comment by pangflash** [comment]
I found flash_api.h,But I don't know how to use it. Where is an example program? I want to learn it. Thank you

**Comment by facchinm** [comment]
Hi @pangflash ,
you can use mbed's APIs following something like this example https://github.com/arduino/ArduinoCore-mbed/issues/239#issuecomment-849403089 .
We'll improve the documentation soon, sorry for that.

**Comment by pangflash** [comment]
@facchinm 
thank you 。
