### ISSUE TITLE
CAN interrupt callback does not work in Portenta H7

### ISSUE THREAD

**Issue by abyanu** [arduino/ArduinoCore-mbed#308]
After initializing and attaching a callback interrupt handler for CAN it never gets called. But message is received when polled 
//Initialization
CAN can1(PB_8, PH_13, 500000);

//In Setup
can1.attach(callback(&OnRxMessage),CAN::RxIrq );

//Callback function
static void OnRxMessage(void)
{
  Serial.print("CAN message received interrput: "); 
  
  if(can1.read(rxMsg))
  {
    Serial.print("CAN message received: "); 
    Serial.println(rxMsg.data[0]);
  } 
}

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino/ArduinoCore-mbed/blob/master/patches/0171-can-stm32-use-FDCAN_IT_RX_FIFO0_NEW_MESSAGE-for-RX-i.patch , released as core 3.2.0
