### ISSUE TITLE
Question: How do I use hardware JPEG codec on Portenta H7?

### ISSUE THREAD

**Issue by tokiedokie** [arduino/ArduinoCore-mbed#324]
Portenta H7 has hardware JPEG codec. However I cannot find any example codes that encode/decode jpeg for arduino.
I want to encode jpeg file from Flash storage.
How do I encode/decode jpeg using hardware JPEG codec?

**Comment by facchinm** [comment]
Hi @tokiedokie ,
there is no ready-made Arduino example since we've not been using that functionality yet.
However, you can use the awesome openmv wrapper (https://github.com/openmv/openmv/blob/a7e0e23bce73e3a7db4ede392fc4c3ea4279a9da/src/omv/imlib/jpeg.c#L962-L1275) with very little modifications.
Just keep in mind that if you include functions in an Arduino sketch you must prepend the functions with `extern "C"`, otherwise they won't be linked and nothing will work :wink:

**Comment by tokiedokie** [comment]
Hi @facchinm,
Thank you for your reply.
I read the code and I tried to implement to my code but I couldn't do it.
I will use a existing JPEG decode library at this time.

**Comment by hpssjellis** [comment]
Just thought I would add to this closed Issue. While searching the stm32 documents at 

https://www.st.com/resource/en/datasheet/stm32h747xi.pdf

I found this about the hardware 

![image](https://user-images.githubusercontent.com/5605614/217443359-674902b0-78fe-4b86-8636-0a9ec1a5973d.png)

Curious what @bitbank2 the maker of [JPEGDEC](https://github.com/bitbank2/) and [JPEGENC](https://github.com/bitbank2/JPEGENC) has to say about the Portenta JPEG hardware. 

I have already used his [PNGenc](https://github.com/bitbank2/PNGenc) library to get PNG images saved to SD card on the portenta [here](https://github.com/hpssjellis/portenta-pro-community-solutions/blob/main/examples/dot3-portenta-vision-shields/dot36-camera-png-to-web/dot362-png-to-sd-card/dot362-png-to-sd-card.ino)

**Comment by bitbank2** [comment]
The hardware JPEG codec of the STM32 is used in OpenMV. I optimized that code and the hardware outperforms software encoding/decoding if you feed it data efficiently. As @facchinm says, the best place to see how to use the STM32 JPEG hardware is in the OpenMV code.

**Comment by metanav** [comment]
> Hi @tokiedokie , there is no ready-made Arduino example since we've not been using that functionality yet. However, you can use the awesome openmv wrapper (https://github.com/openmv/openmv/blob/a7e0e23bce73e3a7db4ede392fc4c3ea4279a9da/src/omv/imlib/jpeg.c#L962-L1275) with very little modifications. Just keep in mind that if you include functions in an Arduino sketch you must prepend the functions with `extern "C"`, otherwise they won't be linked and nothing will work 😉

I am interested in having the ArduinoCore Mbed include support for JPEG hardware encode/decode. I attempted to implement it using the OpenMV code or directly from the STM32CubeH7 examples, but they were unsuccessful with Mbed. With the introduction of the Giga R1 Display shield, direct support of this kind is necessary.

**Comment by bitbank2** [comment]
@metanav if hardware JPEG decode isn't a 'hard' requirement, my JPEGDEC software decoder can work with any size image. The default buffer sizes are to allow it to run on devices with 20K SRAM or more.

**Comment by metanav** [comment]
> @metanav If hardware JPEG decode isn't a 'hard' requirement, my JPEGDEC software decoder can work with any size image. The default buffer sizes are to allow it to run on devices with 20K SRAM or more.

Thanks, @bitbank2 for your reply. I needed hardware JPEG decoding to render fast-moving frames in RGB565 800x480 pixels at 25 fps. However, this seems implausible with software decoding.

**Comment by bitbank2** [comment]
It may be possible, but it will be mostly dependent on the quality setting of the images. Large, high quality frames will decode more slowly than small low quality frames.
