### ISSUE TITLE
mbed: v1.2.2 - whd_print_logbuffer() not found

### ISSUE THREAD

**Issue by jwestmoreland** [arduino/ArduinoCore-mbed#34]
Maybe this is just me - I had a 'glitch' when the 1.2.1 update to 1.2.2 occurred - but is anyone else seeing this:

c:\tmp\Display/Display.ino:503: undefined reference to `whd_print_logbuffer'
c:\AppData\Local\Temp\arduino_build_968917\libraries\WiFi\WiFi.cpp.o: In function `wiced_filesystem_mount':
C:\Users\john\AppData\Local\Arduino15\packages\arduino-beta\hardware\mbed\1.2.2\libraries\WiFi\src/WiFi.cpp:294: undefined reference to `whd_print_logbuffer'

Thanks,
John
P.S. - Appears the file write was successful, though:
Sketch uses 276228 bytes (35%) of program storage space. Maximum is 786432 bytes.
Global variables use 65000 bytes (12%) of dynamic memory, leaving 458624 bytes for local variables. Maximum is 523624 bytes.

**Comment by facchinm** [comment]
I think you might have a stray WiFi.cpp from previous experimentation (`wiced_filesystem_mount` comes from https://github.com/arduino/ArduinoCore-mbed/pull/26).
Try cleaning up the folder (by uninstalling and reinstalling 1.2.2) and let me know if it works :wink:

**Comment by jwestmoreland** [comment]
Martino,

Is the QSPI update in 1.2.2?  When I downloaded it, I wasn't sure - but again, yes, I probably need to redownload.
I didn't see the PortentaWiFiFirmwareUpdater.ino in the mbed 1.2.2 update that downloaded.

Thanks,
John

**Comment by jwestmoreland** [comment]
Also - I should have put in OP - I call whd_print_logbuffer() in my app and it errors there also.

**Comment by jwestmoreland** [comment]
Martino,

OK - this is interesting - I have all of the whd_print_logbuffer() calls commented out - but I do have this in my code:
REDIRECT_STDOUT_TO(Serial);

And, I just saw this on com port (Serial) output:

01:31:23.642 -> WLAN MAC Address : C4:AC:59:4A:29:56
01:31:23.642 -> WLAN Firmware    : wl0: Jan 30 2020 21:41:53 version 7.45.98.95 (r724303 CY) FWID 01-5afc8c1e
01:31:23.675 -> WLAN CLM         : API: 12.2 Data: 9.10.39 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2020-01-30 21:30:05 
01:31:23.675 -> WHD VERSION      : v1.91.2 : v1.91.2 : GCC 10.1 : 2020-06-25 02:15:47 -0500
01:31:29.388 -> Restart single access loop count 99851  stat 4
01:31:29.872 -> Restart single access loop count 99851  stat 4
01:31:30.388 -> Restart single access loop count 99850  stat 4
01:31:30.873 -> Restart single access loop count 99850  stat 4

And, wifi is working.

Hmmm.

Regards,
John

**Comment by facchinm** [comment]
WHD VERSION : v1.91.2 means you are on this https://github.com/arduino/ArduinoCore-mbed/pull/26 probably.
Did you try reinstalling completely the core?

**Comment by jwestmoreland** [comment]
Martino,

Yes - I know the QSPI device was written.

And, yes, I did, and whd_print_logbuffer() is AOK in 1.2.2 or at least doesn't fail compiling.

So, when will  #26 be included in 'main download'?

Thanks,
John

**Comment by facchinm** [comment]
I'm probably going to merge it today but I have to make sure 1.2.2 is fine before doing so :wink:

**Comment by jwestmoreland** [comment]
OK Martino!
Thanks,
John
