### ISSUE TITLE
Add internal pins to Nicla Sense's pin map

### ISSUE THREAD

**Issue by kgoveas** [arduino/ArduinoCore-mbed#358]
The following pins need to be added in [g_APinDescription](https://github.com/arduino/ArduinoCore-mbed/blob/master/variants/NICLA/variant.cpp#L88) to be accessed using Arduino wiringDigital APIs. 

- INT_ESLOV (GPIO35) : P0_19
- RESET_BHI260 (GPIO16) : P0_18
- INT_BHI260 (GPIO13) : P0_14
- BQ_CD (GPIO30) : P0_25
- CS_FLASH (GPIO31) : P0_26
- CS_BHI260 (GPIO25) : P0_31

**Comment by facchinm** [comment]
Fixed by #359
