### ISSUE TITLE
portenta h7 BootLoader source repeat

### ISSUE THREAD

**Issue by bm16ton** [arduino/ArduinoCore-mbed#370]
Did uhm we ever get anywhere on the source code for portenta? Even a statement explaining if or not it will actually happen. Unless Im mistaken and it is available sumwhere? I cant imagine it would be difficult to push to github....so licensing? Or maybe the cure to cancer is hidden in the code and you dont wanna bring down the medical establishment? Else my mother told you not to give it to me! Dont listen to that b**ch, ask her about the game shes played with the neighbors back in 70s with car keys in a fish bowl. Spoiler its gross! So anyway I hope this post was as nonsensical and confusing as your guys lack of comments and source code for our boot loader (actually you guys made it clear its not "our" bootloader but all yours) Wish I had looked into this before purchasing the board, for me way too expensive for caveats.

**Comment by olback** [comment]
See https://github.com/arduino/ArduinoCore-mbed/issues/37#issuecomment-1018586044.
