### ISSUE TITLE
Action error when run the workflow

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/ArduinoCore-mbed#383]
Hi 
I download the board and run those examples all can work. but the workflow of action still reports those examples still exist problem, could you help with it, thank you.

![image](https://user-images.githubusercontent.com/47217650/148709660-b1d24fbc-16f0-4667-b6ab-514594c76b64.png)

Best regards

**Comment by 0hotpotman0** [comment]
this is the link : https://github.com/Seeed-Studio/ArduinoCore-mbed/runs/4749036455?check_suite_focus=true

**Comment by facchinm** [comment]
Hi @0hotpotman0 ,
it looks like the issue is 
`Error during build: exec: "adafruit-nrfutil": executable file not found in $PATH` .
You may need to add a command to install that utility (via a core that provides it) in the workflow file.
