### ISSUE TITLE
Action release error: "cannot stat '../*.tar.bz2': No such file or directory"

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/ArduinoCore-mbed#385]
Hi   
I see your release of action always fails after version 1.3.2, 

And I check the log, there look like missed a tar.bz2 file 
![image](https://user-images.githubusercontent.com/47217650/149744062-8cf6f42b-bc95-4a66-ba73-22067d7f75fe.png)

Is that possible to fix?

Best regards

**Comment by facchinm** [comment]
The `release` action is broken due to this line https://github.com/arduino/ArduinoCore-mbed/blob/master/extras/pack.release.bash#L28-L30 ; since the script to package the cores is really this (https://github.com/arduino/ArduinoCore-mbed/blob/master/package_full.sh ) the action is not being used at the moment and can be removed safely.

**Comment by 0hotpotman0** [comment]
> The `release` action is broken due to this line https://github.com/arduino/ArduinoCore-mbed/blob/master/extras/pack.release.bash#L28-L30 ; since the script to package the cores is really this (https://github.com/arduino/ArduinoCore-mbed/blob/master/package_full.sh ) the action is not being used at the moment and can be removed safely.

I try to give a fixed version as the latest version 2.6.1, It pass that step, but the new error as below :
![image](https://user-images.githubusercontent.com/47217650/149896647-55ce9feb-a826-4a47-bdb4-39bfe39deddf.png)
![image](https://user-images.githubusercontent.com/47217650/149896781-859a6f37-f48d-4494-b541-eb1414e9adc7.png)

It looks like cannot access the server, I think it is just upload the package something to JSON and tar.bz2 file, So I try to disable it, then next step some files cannot available again

![image](https://user-images.githubusercontent.com/47217650/149898085-a7c98bf6-ee33-4ff6-a51e-fcbc0e26a1cf.png)

So the main problem is accessing the server to get json I think, could give me some solve, maybe some points I do not do right 

Best regards
