### ISSUE TITLE
The `release` action is broken

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/ArduinoCore-mbed#386]
> The `release` action is broken due to this line https://github.com/arduino/ArduinoCore-mbed/blob/master/extras/pack.release.bash#L28-L30 ; since the script to package the cores is really this (https://github.com/arduino/ArduinoCore-mbed/blob/master/package_full.sh ) the action is not being used at the moment and can be removed safely.

I try to give a fixed version as the latest version 2.6.1, It pass that step, but the new error as below :
![image](https://user-images.githubusercontent.com/47217650/149896647-55ce9feb-a826-4a47-bdb4-39bfe39deddf.png)
![image](https://user-images.githubusercontent.com/47217650/149896781-859a6f37-f48d-4494-b541-eb1414e9adc7.png)

It looks like cannot access the server, I think it is just upload the package something to JSON and tar.bz2 file, So I try to disable it, then next step some files cannot available again

![image](https://user-images.githubusercontent.com/47217650/149898085-a7c98bf6-ee33-4ff6-a51e-fcbc0e26a1cf.png)

So the main issue is the program can not access the server download the  JSON I think, could give me some solution, maybe some points I do not do right or understand wrong.

Best regards

_Originally posted by @0hotpotman0 in https://github.com/arduino/ArduinoCore-mbed/issues/385#issuecomment-1015172955_

**Comment by facchinm** [comment]
Hi @0hotpotman0 ,
of course you can't push to our downloads servers :slightly_smiling_face: This would be a tiny tiny security issue :wink: 
However, for your own fork, you can modify the lines to push the artifacts to another service of your choice (even github)
