### ISSUE TITLE
ArduinoCore nRF528x mbedos Vs ArduinoCore mbed

### ISSUE THREAD

**Issue by sabas1080** [arduino/ArduinoCore-mbed#39]
What is the difference between [ArduinoCore-nRF528x-mbedos](https://github.com/arduino/ArduinoCore-nRF528x-mbedos) and this repo?

I see nano ble 33 in the two repos

Thanks

**Comment by aentinger** [comment]
As I understand it the future support for Nano 33 BLE will be only added to ArduinoCore-mbed while ArduinoCore-nRF528x-mbedos will be deprecated. @facchinm may contradict me if I'm wrong.

**Comment by sabas1080** [comment]
ok, thanks!
