### ISSUE TITLE
wiring_analog.cpp fails to build after running ./mbed-os-to-arduino -r on Nano 33 BLE

### ISSUE THREAD

**Issue by ipener** [arduino/ArduinoCore-mbed#390]
**OS**: Mac
**Board**: Arduino Nano 33 BLE
**IDE**: Arduino IDE Version: 2.0.0-rc3
**Mbed OS**: Version 2.6.1

**Context**
I need to rebuild the mbed core in order to set a higher ATT MTU for BLE requests. As the [README.md](https://github.com/arduino/ArduinoCore-mbed/blob/master/README.md) suggests, I need to use `./mbed-os-to-arduino` which unfortunately doesn't work out of the box on a Mac (Bash version too low, Python3 missing, etc.). After getting It to work eventually, I'm able to compile the latest version on Mbed OS.

**Problem**
However, I get two build failures:

```
/Library/Arduino15/packages/arduino/hardware/mbed_nano/2.6.1/cores/arduino/Arduino.h:98:8: error: 'analogin_config_t' does not name a type; did you mean 'analogin_config_s'?
 extern analogin_config_t adcCurrentConfig;
        ^~~~~~~~~~~~~~~~~
        analogin_config_s

/Library/Arduino15/packages/arduino/hardware/mbed_nano/2.6.1/cores/arduino/wiring_analog.cpp: In function 'int analogRead(pin_size_t)':
/Library/Arduino15/packages/arduino/hardware/mbed_nano/2.6.1/cores/arduino/wiring_analog.cpp:114:12: error: 'class mbed::AnalogIn' has no member named 'configure'
       adc->configure(adcCurrentConfig);
            ^~~~~~~~~
/Library/Arduino15/packages/arduino/hardware/mbed_nano/2.6.1/cores/arduino/wiring_analog.cpp: In function 'void analogUpdate()':
/Library/Arduino15/packages/arduino/hardware/mbed_nano/2.6.1/cores/arduino/wiring_analog.cpp:129:29: error: 'class mbed::AnalogIn' has no member named 'configure'
       analogPinToAdcObj(i)->configure(adcCurrentConfig);
                             ^~~~~~~~~
```

Now, I've gone through the [ARMmbed/mbed-os](https://github.com/ARMmbed/mbed-os) repo and neither `analogin_config_t` nor the `configure(1)` method is defined. Have a look at [AnalogIn.h](https://github.com/arduino/ArduinoCore-mbed/blob/master/cores/arduino/mbed/drivers/include/drivers/AnalogIn.h) in the ArduinoCore-mbed repo vs. [AnalogIn.h](https://github.com/ARMmbed/mbed-os/blob/0c6753bb821612eb72b5f682aed7ffcc98e80a1f/drivers/include/drivers/AnalogIn.h) in the mbed-os repo. I've also tried checking out mbed-ps version 6.8.0 since this is the last version ArduinoCore-mbed was built with but the issue persists.

I can fix the first problem but not the second. Either I'm missing something or there's a patch to the mbed-os core that is applied. Hope someone can point me to a clean way to get this to work (on a Mac).

**Comment by facchinm** [comment]
Hi @ipener ,
sorry for the late response. Some out-of-tree patches needed to adapt mbed-so to our build are contained in `patches` folder. Not all of them are strictly needed (and some have been mainlined) but the one you need is https://github.com/arduino/ArduinoCore-mbed/blob/master/patches/0004-Add-AnalogIn-configure-function.patch . Just apply it over any mbed-os version (the Nordic porting layer has not being updated in a while) and then everything should be ok.

About porting `mbed-os-to-arduino` script to run on Mac @manchoz had some patches lying around that may be useful

**Comment by AllisonSimpson** [comment]
How did you manage to solve the analogin_config_t issue?
