### ISSUE TITLE
digitalWrite(D6, High) produces weak signal on Nano 33 BLE

### ISSUE THREAD

**Issue by ipener** [arduino/ArduinoCore-mbed#391]
**OS**: Mac
**Board**: Arduino Nano 33 BLE
**IDE**: Arduino IDE Version: 2.0.0-rc3
**Mbed OS**: Version 2.6.1

**Context**
I've correctly wired up an Arduino Nano 33 BLE to a [4-channel AC dimmer from RobotDyn](https://robotdyn.com/ac-light-dimmer-module-4-channel-3-3v-5v-logic-ac-50-60hz-220v-110v.html) and noticed that the output signal produced by calling `digitalWrite(D6, HIGH)` is oscillating which results in the LED being dim. In contrast, the signal is not oscillating and the LED is very brighter when replacing the board with an Arduino Nano 33 IoT.

**Problem**
Here's the code snippet to reproduce the issue:
```
void setup() {
  pinMode(D6, OUTPUT);
  digitalWrite(D6, HIGH);
}

void loop() {}
```

This has been raised in the [Arduino forum](https://forum.arduino.cc/t/ble-interference-with-digitalwrite/635822) and apparently fixed on the [ArduinoCore-nRF528x-mbedos](https://github.com/arduino/ArduinoCore-nRF528x-mbedos/issues/65) repo. However, going through the code I don't think that's actually the case.

This produces the same result and doesn't use any Arduino code from what I can tell:
```
#include "hal/gpio_api.h"

void setup() {
  gpio_t gpio;
  gpio_init_out_ex(&gpio, (PinName)D6, 1);
}
```
I've tried pins D3 to D6 and the results are the same. According to the [Nano 33 BLE specs](https://docs.arduino.cc/hardware/nano-33-ble) the I/O voltage is 3.3V but compared to the Nano 33 IoT this doesn't seen the case. I hope I'm wrong and this is indeed a software issue. If so, please confirm/verify/or point to a fix if possible.

**Comment by Cdo-Github** [comment]
I have a similar problem that the digitalWrite function work once only. After sending HIGH I don't get it LOW.

**Comment by ipener** [comment]
Closing since this is expected behavior. Turns out that the [Arduino Nano 33 BLE](https://docs.arduino.cc/hardware/nano-33-ble) outputs 7mA (not 10mA as stated in the spec) and the [Arduino Nano 33 IoT](https://docs.arduino.cc/hardware/nano-33-iot) outputs 10mA (not 7mA as stated in the spec).

**Comment by facchinm** [comment]
> Closing since this is expected behavior. Turns out that the [Arduino Nano 33 BLE](https://docs.arduino.cc/hardware/nano-33-ble) outputs 7mA (not 10mA as stated in the spec) and the [Arduino Nano 33 IoT](https://docs.arduino.cc/hardware/nano-33-iot) outputs 10mA (not 7mA as stated in the spec).

We should indeed fix the documentation @sebromero
