### ISSUE TITLE
Can’t run code in custom H7 board.

### ISSUE THREAD

**Issue by kikolobo** [arduino/ArduinoCore-mbed#395]
Hello everyone.

We can’t run arduino code in a custom built H7 board. We can run cube code though. A simple blink sketch won’t do it from arduino but if we create a program in the cube to do the same it works ok. Pinout is identical to portenta, and that’s the board we select in the arduino IDE.

We program the chip without boot loader using the programmer option in the IDE.  Programming finishes ok but It just don’t run the code. We even tried doing a high / low sequence on all pins.

We have set the boot registers for start address either to 0x8040000 or the beginning of the memory without luck.  My guess is that the bootloader is at that address and it jumps somewhere else from the BL to start the custom code at another address but since we are not using the BL it just halts there. Or I really don’t know.

Any idea what we might be doing wrong?

Any help would be greatly appreciated we are pulling out hair here. 😊

**Comment by facchinm** [comment]
Bootloader for Portenta H7 is finally live https://blog.arduino.cc/2022/04/12/introducing-the-arduino-secure-boot/ , you can use it an an inspiration for your board :wink:
