### ISSUE TITLE
Programming Pico with Thonny in Mac OSX

### ISSUE THREAD

**Issue by SirDoug1971** [arduino/ArduinoCore-mbed#397]
Following the advice to connect an RPi Pico with an iMac while holding down the BOOTSEL button, I don't see an RPI-RP2 drive appear on the desktop, but I do see the following message (in red)  in Thonny:

"Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL."

I've waited before trying the 2nd and 3rd options. The third option produces an additional message (in red):

"WARNING:root: Unexpected echo. Expected b'%Run -c $EDITOR_CONTENT\r\n', got b''

Naturally, I have selected "MicroPython (RaspberryPi Pico) bottom left in Thonny.

I should be most grateful for any clues on what to do next.

**Comment by facchinm** [comment]
Hi @SirDoug1971 ,
this repo is only supporting the RPi Pico within the Arduino environment. You'll probably find some more answers asking support on https://github.com/thonny/thonny or https://github.com/raspberrypi/pico-sdk
