### ISSUE TITLE
Does the PDM library support stereo mode?

### ISSUE THREAD

**Issue by nerodu** [arduino/ArduinoCore-mbed#403]
Hi

It is good to use the PDM library for my test. However, it seems like just one channel is supported, am I right? 
![image](https://user-images.githubusercontent.com/69945444/154432985-d804ec55-12f5-4d26-b356-7401df0dfddf.png)

**Comment by facchinm** [comment]
Hi @nerodu ,
2 channels are supported only on the Portenta (using Vision shield https://store.arduino.cc/products/arduino-portenta-vision-shield-lora%C2%AE ) . All the other boards come with a mono mic, so while the library should already be compatible with stereo channels there may be some some subtle bugs lurking around :wink:
