### ISSUE TITLE
Raspberry pi pico while(!Serial) bug

### ISSUE THREAD

**Issue by qwec01** [arduino/ArduinoCore-mbed#406]
Hi,
I'm using Rpi PICO with arduino IDE 1.8.19, when using Serial (USB port), my code stuck in  while(!Serial) at first power on, but when I  open Serial Monitor (maybe resets the pico), my code can run with no problem. If I change Serial to Serial1 (UART at pin0 and1), or comment out "while(!Serial)" line, my code can run with no problem, Serial and Serial1 are working with no problem. I think this maybe a bug. Here's my code.
`void setup() {`
`  pinMode(LED_BUILTIN, OUTPUT);`
`  digitalWrite(LED_BUILTIN, HIGH);`
`  Serial.begin(9600);`
`  while(!Serial);`
`  digitalWrite(LED_BUILTIN, LOW);`
`}`
Thanks!

**Comment by facchinm** [comment]
Hi @qwec01 ,
it is totally expected.
`while !Serial` construct has been historically introduce the try to match the behavior of UNO (which resets and restarts the sketch every time you open the serial port).
In case of USB based serial ports, we cannot reset safely the board but we just wait for the user to open it to avoid losing prints.
`Serial1` on the other hand is an hardware serial port, so waiting for it to be open makes no sense, hence the `while !Serial1` returns immediately.
