### ISSUE TITLE
Read Out Protection

### ISSUE THREAD

**Issue by rdockterjr** [arduino/ArduinoCore-mbed#41]
I know the STM32H747 chip has various levels of read/write protection available. I believe this functionality is usually enabled by setting certain registers via the ST Link CLI utility. Is there any plan to make this functionality available within the Arduino/mbed programmer?

**Comment by facchinm** [comment]
Hi @rdockterjr ,
setting the user bits can be done via programmer (like this https://github.com/arduino/ArduinoCore-mbed/blob/master/boards.txt#L47 ) or via user code (it's a bit convoluted in that case).
There's no plan actually to add this functionality to the end user though :slightly_smiling_face:
