### ISSUE TITLE
How to debug Nicla Sense ME by Jlink or something else?

### ISSUE THREAD

**Issue by leomonan** [arduino/ArduinoCore-mbed#426]
Hello, 
  I got some crash problems when integrating Nicla Sense ME to our system, for Arduino Nano 33BLE I know how to debug it using Jlink. 
  Do we have some similar way to do the On Circle Simulation debug on Nicla Sense ME?
  Thanks!

**Comment by facchinm** [comment]
There's no need to use a Jlink on the Nicla since the USB port already exposes a debug interface on the D11 "companion chip".
To create a gdb server you can run in a terminal
```
/home/$(whoami)/.arduino15/packages/arduino/tools/openocd/0.11.0-arduino2/bin/openocd -d2 -s /home/$(whoami)/.arduino15/packages/arduino/tools/openocd/0.11.0-arduino2/share/openocd/scripts/ -f interface/cmsis-dap.cfg -c "transport select swd; adapter speed 1000" -f target/nrf52.cfg
```
And then you can connect via `gdb` on port 3333.

If you need any further instruction let me know!
