### ISSUE TITLE
[Portenta_H7] Ethernet not working in core v3.0.0

### ISSUE THREAD

**Issue by khoih-prog** [arduino/ArduinoCore-mbed#436]
#### Describe the bug

The core's Ethernet library example [**WebClient**](https://github.com/arduino/ArduinoCore-mbed/tree/master/libraries/Ethernet/examples/WebClient) is working normally for core v2.8.0-

For `core v3.0.0`, the same example just hangs at `Ethernet.begin()`

#### MRE

Using the following core's Ethernet library example [**WebClient**](https://github.com/arduino/ArduinoCore-mbed/tree/master/libraries/Ethernet/examples/WebClient) with 

- Arduino IDE v1.8.19
- mbed_portenta `core v3.0.0` or `core v2.8.0`
- Portenta_H7_M7

#### Terminal

1. When using core v2.8.0

```
Initialize Ethernet with DHCP:
  DHCP assigned IP 192.168.2.133
connecting to www.google.com...
connected to 172.217.1.4
HTTP/1.1 200 OK
Content-Type: text/html; charset=ISO-8859-1
Date: Fri, 25 Mar 2022 16:29:30 GMT
Expires: -1
Cache-Control: private, max-age=0
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: 1P_JAR=2022-03-25-16; expires=Sun, 24-Apr-2022 16:29:30 GMT; path=/; domain=.google.com; Secure
Set-Cookie: AEC=AVQQ_LA6Vda9ApFdLtCbD6JCYwsEkhUFAoiir-NH5itjaAgpkd3-eQKv56M; expires=Wed, 21-Sep-2022 16:29:30 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
Set-Cookie: NID=511=exvhT6NxCtgXm6YY1bXHyEhXY_5BIXf3ruelN-u9J-CDkRySMM6JDcYII1Vt4ay7Z7t6n7tU5jn91tZ7F0mHli-TNS6SoP7obMDxAVEol-e2mbH47cqREQcThcBXwd6ApRF9t_wp_hRoqNZlXkIdpjaeux86g4-8ZVJy4UTyCZQ; expires=Sat, 24-Sep-2022 16:29:30 GMT; path=/; domain=.google.com; HttpOnly
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close
Transfer-Encoding: chunked
...
```

2. For core v3.0.0, the same example just hangs at `Ethernet.begin()` and displays

```
Initialize Ethernet with DHCP:
```

#### More info

Any Ethernet-related code hangs at this line

https://github.com/arduino/ArduinoCore-mbed/blob/6c3abc9e2e679eed1b1ec51861ca982c70595c61/libraries/Ethernet/src/Ethernet.cpp#L14

**Comment by giulcioffi** [comment]
Hi @khoih-prog, the issue should be now solved with the latest release **3.0.1** :) Can you test it an provide a feedback? Thanks!
