### ISSUE TITLE
[RP2040] Built in mbedtls does not have ctr_drbg and entropy enabled

### ISSUE THREAD

**Issue by dogtopus** [arduino/ArduinoCore-mbed#437]
I'm trying to use the built-in mbedtls (on RP2040) to do RSA PSS signing, which requires an RNG function. Unfortunately I found that when I try to use  ctr_drbg and entropy API the linker gives me the "undefined reference" error.

It also seems hard to workaround this issue by using external mbedtls due to symbol conflicts. I'd also avoid switching to another crypto library at this point due to the fact that I already wrote a bunch of mbedtls specific code.

**Comment by dogtopus** [comment]
It seems to be worse than I initially thought. IIRC some versions of TLS uses RSA PSS so I ran nm on all the the libmbed.a targeting supported boards, and found that only RP2040 have those APIs missing, and looks like they also don't have SSL/TLS support. This includes Nano RP2040 connect which has onboard wifi.

**Comment by facchinm** [comment]
Hi @dogtopus ,
sorry for the inconvenience. Can you paste a snippet that triggers the  "undefined reference" error so I can tune our mbedtls config for RP2040 and get it included? Thanks

**Comment by facchinm** [comment]
Nano RP2040 uses the onboard ESP32 module to perform TLS so it doesn't use any mbedtls functionality "directly"

**Comment by dogtopus** [comment]
What I have is currently somewhat like this:

```c++
#include <mbedtls/entropy.h>
#include <mbedtls/ctr_drbg.h>

static mbedtls_ctr_drbg_context drbg;
static mbedtls_entropy_context entropy;
//static mbedtls_rsa_context rsa;

const uint8_t DRBG_CUSTOM[] = "CUSTOM";

int my_entropy_source(void *ctx, uint8_t *buf, size_t buflen, size_t *outlen) {
    // TODO implement this
    return MBEDTLS_ERR_ENTROPY_SOURCE_FAILED;
}

bool initRNG() {
    int mbedtlsError;

    mbedtls_entropy_init(&entropy);
    mbedtlsError = mbedtls_entropy_add_source(&entropy, my_entropy_source, nullptr, 32, MBEDTLS_ENTROPY_SOURCE_STRONG);
    if (mbedtlsError != 0) {
        Serial.print("mbedtls_entropy_add_source() -> ");
        Serial.println(mbedtlsError, 16);
        return false;
    }

    mbedtls_ctr_drbg_init(&drbg);
    mbedtlsError = mbedtls_ctr_drbg_seed(&drbg, mbedtls_entropy_func, &entropy, DRBG_CUSTOM, sizeof(DRBG_CUSTOM));
    if (mbedtlsError != 0) {
        Serial.print("mbedtls_ctr_drbg_seed() -> ");
        Serial.println(mbedtlsError, 16);
        return false;
    }

    return true;
}

void setup() {
    initRNG();
    uint8_t obuf[32];
    mbedtls_ctr_drbg_random(&drbg, obuf, sizeof(obuf));

    /*
    uint8_t sig[256];
    uint8_t hash[32];

    // TODO setup md, hash the data and save it to hash

    mbedtls_rsa_rsassa_pss_sign(
        &rsa,
        mbedtls_ctr_drbg_random,
        &drbg,
        MBEDTLS_RSA_PRIVATE,
        MBEDTLS_MD_SHA256,
        sizeof(hash),
        hash,
        sig
    );
    */
}

void loop() {}
```

Also it might be a good idea to also enable [custom NV seed functions](https://tls.mbed.org/kb/how-to/how_to_integrate_nv_seed) and stub them as weak so the user can override these functions themselves to load/save seeds to EEPROM, for example, so the RNG would at least work to some degree painlessly on platforms without reliable hardware RNG (like RP2040).
