### ISSUE TITLE
cant find what keywords are needed for the usbkeyboard.

### ISSUE THREAD

**Issue by chunkywill** [arduino/ArduinoCore-mbed#443]
is there not a way to hold and press multiple keys, and if so how do i do this.
i also cant find a sheet showing all the commands and keywords.
also is there a gui button option

**Comment by facchinm** [comment]
Hi @chunkywill ,
the APIs for USBKeyboard are listed here https://os.mbed.com/docs/mbed-os/v6.15/apis/usbkeyboard.html .
To send multiple keys, you can either use `keyCode(key, modifier)` or create your own HID report (much more complex and powerful)

**Comment by chunkywill** [comment]
thanks but is there no gui

**Comment by chunkywill** [comment]
how would i create my own hid report?
