### ISSUE TITLE
PortentaH7 not working with Simple http form POST

### ISSUE THREAD

**Issue by hpssjellis** [arduino/ArduinoCore-mbed#444]
The PortentaH7 does not work with a simple http POST of form data using the Arduino-HttpClient.  I filed an issue at the github

https://github.com/arduino-libraries/ArduinoHttpClient/issues/129

Anyone have any suggestions?

**Comment by facchinm** [comment]
Should be fixed by https://github.com/arduino/ArduinoCore-mbed/pull/439
