### ISSUE TITLE
When did the SPI default pins change?

### ISSUE THREAD

**Issue by Dresch123** [arduino/ArduinoCore-mbed#452]
I have been using the standard SPI pins for SD card IO: MISO 4, CLK 2, MOSI 3 and CS 5 for months. All of a sudden, my SD card slot on the Pico Pi's stopped working. It appears an update sometime in March changed the SPI pins to something in the 19 range (sorry I don't know the exact pins because I was too angry while setting them back to the original Mbed "standard".) Ugh.

Hope this helps someone else. I ended up de-soldering and throwing away an SD card slot on my Pico Pi set up because I was convinced it had gone bad...

Some kind of warning about changes like this would be nice.

**Comment by facchinm** [comment]
Hi @Dresch123 ,
sorry to hear that :disappointed: 
We swapped the default SPI/I2C pins on the Pico with this release https://github.com/arduino/ArduinoCore-mbed/releases/tag/2.7.2 after merging https://github.com/arduino/ArduinoCore-mbed/pull/393 .

The release notes reported the change but we have no way to show them when the user updates a core (on IDE 2 we have the chance to get this right but I think there's no such integration yet).
