### ISSUE TITLE
Portenta H7: analogReference(DEFAULT) error: 'DEFAULT' was not declared in this scope

### ISSUE THREAD

**Issue by malmr** [arduino/ArduinoCore-mbed#464]
analogReference(DEFAULT);
error: 'DEFAULT' was not declared in this scope

Main goal: use AREF on the Arduino Portenta H7 as external voltage.

**Comment by SympathicCone** [comment]
https://github.com/arduino/ArduinoCore-mbed/pull/465

**Comment by malmr** [comment]
Thanks, perfect!
