### ISSUE TITLE
Use Startup files for Hardware interrupts

### ISSUE THREAD

**Issue by SympathicCone** [arduino/ArduinoCore-mbed#473]
I wish to use the hardware interrupts provided by the stm32h747xI within the portenta, so how and where do I add the startup_stm32h747.s where the IRQHandlers are defined to my code using ArduinoIDE? I am stuck within my project due to that since my code will just look forever for the said Handler and never get out of the interrupt . I looked it up online but no one uses Arduino IDE when it comes to implement .s files.

**Comment by facchinm** [comment]
Hi @SympathicCone ,
can you elaborate a bit more :slightly_smiling_face:  ? The vector table is already defined in the core 
https://github.com/arduino/mbed-os/blob/extrapatches-6.15.1/targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_STM32H747xI_CM7/TOOLCHAIN_GCC_ARM/startup_stm32h747xx.S#L124-L293

To attach your function to an interrupt, after enabling it, you can implement the weak callback (remember the `extern "C"` clause if you are in a `.ino` or `.cpp` file) or hook you function with `NVIC_SetVector`.

Let's say, for example, you want to hook to `LTDC_ER_IRQn` ; you can do it this way
```
extern "C" {
void LTDC_ER_IRQHandler() {
  // do something here
}
}
```
or this way
```
NVIC_SetVector(LTDC_ER_IRQn, (uint32_t)&my_function);
```
