### ISSUE TITLE
Bizarre problem with the Portenta H7

### ISSUE THREAD

**Issue by GunnerDx88** [arduino/ArduinoCore-mbed#474]
Greetings,

Yesterday I was trying to debug on the portenta H7 using the ST-Link. For that, I used the JTAG conenctors + I had the usb cable always connected to the board (not sure if this is okay or not but otherwise the ST-Link was failing). I was able to reprogram the card via the ST-Link yesterday and everything was working fine. This morning I turned on my laptop and I noticed that the RGB led was not working instead the Battery Charger Led on the board was on and on top of that my PC no longer recognizes the Portenta H7 card. It's like it's not even connected. Does anyone know what may be the problem here ? Or are there any possible solutions ?
Any help is appreciated.

Thank you.

**Comment by pennam** [comment]
You have to try to connect while keeping the board under reset and then releasing. You can use [ST-LINK utility](https://www.st.com/en/development-tools/stsw-link004.html) if you are on Windows enabling the connect-under-reset option in the settings menu.

**Comment by pennam** [comment]
to connect while keeping the board under reset: press the reset button, connect the usb cable keeping the reset button pressed and connect using ST-LINK utility (or openocd) and then release the reset button.

**Comment by GunnerDx88** [comment]
That did the trick. Thank you so much.

**Comment by pennam** [comment]
Great!
