### ISSUE TITLE
Debugging Nicla Vision 

### ISSUE THREAD

**Issue by simengangstad** [arduino/ArduinoCore-mbed#479]
Hello,

Is there functionality for debugging the Nicla Vision over USB as one can do with the Nicla Sense Me? I see that the Nicla Sense Me has an ATSAM for providing debug functionality over USB, but as far I can see in the data sheet, this isn't the case for the Nicla Vision. If JTAG is the only option, which connector would one use which would fit on the pads on the board without soldering? The data sheet mentions that a 50 mil header can be used without soldering, but I can't seem to find a 50 mil connector which would be able to "clamp" on to those pads.

**Comment by giulcioffi** [comment]
Hi @simengangstad, as you said Nicla Sense ME can be debugged over USB thanks to the samd11 onboard, while you cannot do the same with Nicla Vision. However a debug interface is available of Nicla Vision fingers, which are accessible with 2 rows 1.27mm male headers as shown in these pictures.
![Nicla_debug_conn1](https://user-images.githubusercontent.com/46971818/168546181-90c8db6e-9c01-4336-85f9-be900d1ccb6a.jpg)
![Nicla_debug_conn2](https://user-images.githubusercontent.com/46971818/168546200-8b6d628e-61b7-4de8-a8d0-37b5ad74b4e1.jpg)

**Comment by manchoz** [comment]
For future reference:

[How to debug sketches on Nicla Sense ME](https://forum.arduino.cc/t/how-to-debug-sketches-on-nicla-sense-me/1039133)
