### ISSUE TITLE
Arm64 no longer supported? ADB? uhg

### ISSUE THREAD

**Issue by bm16ton** [arduino/ArduinoCore-mbed#492]
Went to update my portenta install to 3.1.1 it tried the first time gave a hundred errors bout missing headers then failed deleting my portenta install, then on a retry it fails because ADB isnt available for arm64 in your json...uhg shakes head at this nightmare of an expensive board. I assume that ADB means Android debugging? Why? what new awesome feature is that bringing to the table? Id be happy if all the pwm pins worked fine for now, maybe they do in 3.1.1? Ill simply copy over ADB etc and do a manual install, but im so under impressed with this super over priced crap board i doubt ill put the effort in. Give us small amount of pins wo this stupidly oversized breakout board and sum of those pins are the same pins broken out in multiiple places! Com'on man! A literal laundry list I could go thru, but long short I would just love my $ back so I can go buy a handful of ESP's and still have most of it left over.

**Comment by facchinm** [comment]
Hi @bm16ton ,
the failure to install in arm64 was due to an error on our side and has just been fixed; you should now be able to install core 3.1.1 normally.
`adb` is being used to upload arduino sketches to the new Portenta X8, which is fact is one of the targets in core 3.1.1
