### ISSUE TITLE
Arduino IDE latest version 1.8.19 cannot use pico 2040 borad

### ISSUE THREAD

**Issue by 0hotpotman0** [arduino/ArduinoCore-mbed#496]
Hi
My Arduino IDE version was 1.8.15, and my pico 2040 board can work on this version.
but after I'm updated to the latest version which is 1.8.19, my board cannot upload the program anymore. could you help solve this problem, please?

![image](https://user-images.githubusercontent.com/47217650/172554418-0efd93bf-25f4-4824-8b0e-9116373f62db.png)

Best regards

**Comment by facchinm** [comment]
HI @0hotpotman0 ,
the board is probably stuck running some code that prevents the jump to bootloader (and it's independent from the IDE version).
You can try plugging the Pico while keeping the button pressed; the board will be recognized as a mass storage device (like a usb key) and then you can try reuploading the Blink. Don't worry if no serial port is selected, the procedure will work anyway.

Let me know if it works!
