### ISSUE TITLE
Error creating MCUboot files in OTA partition

### ISSUE THREAD

**Issue by romainreignier** [arduino/ArduinoCore-mbed#515]
I have ran the sketch STM32H747_manageBootloader.ino in order to try MCUBoot bootloader.

But when I try to install it, I have the following error message:
**Error creating MCUboot files in OTA partition**

And the board has the red blink SOS signal.

```
Do you want to install/update the default Arduino bootloader? Y/[n]
Choosing "No", will install/update the MCUboot bootloader.

MCUboot has been selected. Do you want to proceed? Y/[n]

A different bootloader type is available: v6
Do you want to update the bootloader? Y/[n]
Error creating MCUboot files in OTA partition

Creating scratch file
Flashed 0%
```

I have tried directly with the default v21 bootloader and then updated it to v23 but in both case the result is the same.

Do I have to change the flash split setting in the IDE? I have the default 1MB M7 and 1MB M4 setting.

**Comment by pennam** [comment]
Hi @romainreignier,
flash split is not involved in this process. It looks like there is an issue with the QSPI flash. Do you mind to run this [sketch](https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/STM32H747_System/examples/QSPIFormat/QSPIFormat.ino) to format your QSPI flash and then re-run STM32H747_manageBootloader.ino

**Comment by romainreignier** [comment]
Hi @pennam 
Thank you for you fast reply.
Which partition scheme should I use? 1 or 2?

**Comment by pennam** [comment]
both should work, the default scheme is 1

**Comment by romainreignier** [comment]
Ok, thanks.
Maybe a log message should indicate to run this sketch in case of an error in the `STM32H747_manageBootloader.ino` sketch.

**Comment by pennam** [comment]
my plan was to integrate the scratch and update file creaton in the bootloader itself amd remove them from this sketch, but adding a log message is a good idea. Let me know if formatting the QSPI solves your issue.
