### ISSUE TITLE
Problem with arm_math.h functions not included in core

### ISSUE THREAD

**Issue by Soulkrown** [arduino/ArduinoCore-mbed#53]
soulkrown:~/Library/Arduino15/packages/arduino-beta/hardware/mbed/1.2.0/cores $ find . -name "arm_math.h"
./arduino/mbed/cmsis/TARGET_CORTEX_M/arm_math.h

I have this problem when I compile with Mbed OS but not with nRF528x Mbed OS

**Comment by aentinger** [comment]
Alredy referenced in #7 .
