### ISSUE TITLE
Reset mbed enabled Arduino

### ISSUE THREAD

**Issue by martinerk0** [arduino/ArduinoCore-mbed#543]
Is there way to do a software reset / restart with some mbed or other function?

**Comment by facchinm** [comment]
Yup, you can just call `NVIC_SystemReset()` (here, for example, we use it to restart in bootloader mode https://github.com/arduino/ArduinoCore-mbed/blob/505c3d85fc86b09d3de8010a7ab0df271aff998b/variants/ARDUINO_NANO33BLE/variant.cpp#L205
