### ISSUE TITLE
Is at least theoretically possible support for Cortex-M33 (efm32pg22) - how much differ ARMv7M and ARMv8-M ??

### ISSUE THREAD

**Issue by apws** [arduino/ArduinoCore-mbed#545]
Hello, kindly please, can anybody hint for the reply? I mean to use v8-M in similar as v7-M mode, so without trustzone-m involved...
So, how much are both platforms different in ISA and peripherals/registers?
Thanks

**Comment by facchinm** [comment]
Hi @apws ,
mbed-os already supports a few M33 chips (https://github.com/ARMmbed/mbed-os/blob/master/targets/targets.json#L4528-L4536) and also a few EFM32 chips, so I'd say that the driver porting shouldn't be super hard.
Before using this Arduino core you need to port the chip to mbed-os anyway https://os.mbed.com/docs/mbed-os/v6.15/porting/porting-the-hal-apis.html , then all the bindings will be working out of the box.
