### ISSUE TITLE
The ide of Arduino doesn't recognised Arduino Nano 33 ble

### ISSUE THREAD

**Issue by ProgrammerOfPLC** [arduino/ArduinoCore-mbed#550]
In the last days, the ide of Arduino doesn't recognise the Arduino Nano 33 ble board. In _instruments > Port_ don't appear the COM where i have connected the board. The green led on the board is  swithced on and Windows seems to recognised the link because there is the sound  when you connect something to the pc via usb. At this point, i don't understand if the issue is the board or the Ide.
I have already used this board several times and I downloaded all for this type of board the first time i connected.
Have someone alredy have the same problema?

**Comment by facchinm** [comment]
Hi @ProgrammerOfPLC ,
the board has probably been programmed with a sketch that crashes before the board is able to properly enumerate.
To fix this, please double click the reset button (to see the led fading), then it should be recognized by the PC and you can upload a safe sketch
