### ISSUE TITLE
undefined reference to `cyw43_tcpip_link_status'

### ISSUE THREAD

**Issue by lu7did** [arduino/ArduinoCore-mbed#551]
When trying to compile the program ntp-client with the Arduino IDE and after few adaptations to allow for that (comment stdio_init_all() and a couple of castings as well as introduce setup() and loop()) the compilation fails at linking time with the following message

...test\ntp_client/cyw43_arch.c:79: undefined reference to `cyw43_tcpip_link_status'

The prototype for that function is at cyw43.h but including it won't solve the problem
The function itself is at cyw43_lwip.c but it should be in the library path, including it explicitly at the program folder won't solve the problem and actually starts to generate an explosion of dependency issues.

Having search for a similar problem elsewhere but to no avail. It seems a similar issue might prevent the usage of any example on the pico_w path.

I've been working successfully with the IDE, including adaptations of several other examples on the pico-examples path (specially dma, multicore and PIO).

¿Any help or suggestion?

Thanks and best regards, Pedro.

**Comment by facchinm** [comment]
Hi Pedro,
I found [the other issue](https://github.com/raspberrypi/pico-examples/issues/278) you've opened and as I suspected you are not using this core (which doesn't support PicoW) but this one https://github.com/earlephilhower/arduino-pico .
Please reopen the issue there to get support :slightly_smiling_face:
