### ISSUE TITLE
Cannot install the board from IDE anymore

### ISSUE THREAD

**Issue by BluuJo** [arduino/ArduinoCore-mbed#553]
Hello,

Since few days everything messed up while I upgraded to Arduino IDE 2.
I have an Arduino Portenta H7 which worked well since I tried to go to MBED standalone 3.3.0.
When I try to download that from legacy IDE I got an error downloading (see at the bottom of the window):
<img width="804" alt="Capture d’écran 2022-09-21 à 23 24 58" src="https://user-images.githubusercontent.com/103179771/191613327-82c91017-d268-4384-b2cc-2f32fbbbabad.png">

And with the new IDE I am just stuck here:
<img width="1097" alt="Capture d’écran 2022-09-21 à 23 27 16" src="https://user-images.githubusercontent.com/103179771/191613655-d596831c-a695-44c3-b04b-06a731b648ed.png">

I am on a macOS Monterey.

I tried so many thing but here are essentials:
- fresh install (after a complete uninstall)
- on a Windows 10 PC but I got a driver issue which allow me to upload but not see the serial monitor...
- Online editor but I cannot upload (only look at serial monitor)

**Comment by per1234** [comment]
Hi @BluuJo. I saw you also posted over on the Arduino Forum:

https://forum.arduino.cc/t/arduino-ide-not-working-on-macos-anymore/1034541

We'll see if we can help you out over there. I'll make sure to report back here with our findings.

**Comment by facchinm** [comment]
Fixed in the forum thread
