### ISSUE TITLE
Question: It's possible to change USB VID/PID/Serial?

### ISSUE THREAD

**Issue by sonik-br** [arduino/ArduinoCore-mbed#556]
Trying to use custom VID and PID by passing the arguments over the HID class but it just ignores it.
https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/USBHID/src/USBHID.cpp#L121
is there any other way to set VID/PID/Serial (unique name) at runtime?

I'm trying to use the device as a XINPUT and DINPUT game controller. XINPUT requires specific VID and PID.

**Comment by facchinm** [comment]
Hi @sonik-br ,
at the moment the only supported way to change VID/PID is by changing the defines in `pins_arduino.h` that are applied very early in https://github.com/arduino/ArduinoCore-mbed/blob/master/cores/arduino/USB/PluggableUSBDevice.cpp#L301-L305 .
The whole pluggable framework could be enhanced to accept a new pair of vid/pid provided in the constructor of any module but at the moment it's not implemented.
