### ISSUE TITLE
pico not downloading to ide

### ISSUE THREAD

**Issue by mincy69** [arduino/ArduinoCore-mbed#564]
ive been trying to download pico to the ide but it fails and it say the file is corrupt

**Comment by facchinm** [comment]
Hi @mincy69 ,
which tool is telling you that the output is corrupted? Can you please send a full verbose log of the compilation+upload ?

**Comment by mincy69** [comment]
im sorry to waste your time but the boards manager worked but it was arduino ide that was giving troublr because my storage was full fixed storage issue it worked fine thanks for your time have an awesome day
