### ISSUE TITLE
Issue connecting to RP2040 Connect

### ISSUE THREAD

**Issue by RileyNichols** [arduino/ArduinoCore-mbed#565]
I bought an Arduino RP2040 Connect for a school project and it wont turn on. When plugged into my computer it isnt recognizable on ports and wont turn on. Dont know whats wrong with it.

**Comment by facchinm** [comment]
Hi @RileyNichols ,
is the board led yellow LED turning on? If so, you can try a factory reset as explained here https://support.arduino.cc/hc/en-us/articles/4404168794514-Nano-RP2040-Connect-not-being-detected-on-USB-port .
If the yellow led doesn't turn on, please contact support for a replacement.
