### ISSUE TITLE
Updated Firmware - No More Frequent Resets

### ISSUE THREAD

**Issue by jwestmoreland** [arduino/ArduinoCore-mbed#59]
Arduino/Martino,

My Portenta H7 was experiencing frequent resets at times - since I updated to:

[b3e5b1e](https://github.com/arduino/ArduinoCore-mbed/commit/b3e5b1e8e219d0ecc0d03383456f1b1a25e49854)

that issue has gotten a lot better - thought I'd mention that here.

Regards,
John W.

**Comment by sbhklr** [comment]
@jwestmoreland Great! Thanks for your feedback John.
