### ISSUE TITLE
SPI.end() does not check for NULL => crashes NANO33

### ISSUE THREAD

**Issue by RobTillaart** [arduino/ArduinoCore-mbed#590]
First mentioned here https://github.com/RobTillaart/MS5611_SPI/issues/6

## Summary
It should be safe to call SPI.end() before SPI.begin() to allow dynamic change SPI settings.
Now it crashes on the NANO33

#### Current code
From - https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/SPI/SPI.cpp
```cpp

void arduino::MbedSPI::begin() {
    if (dev == NULL) {
      dev = new mbed_spi;
      dev->obj = NULL;
    }
    if (dev->obj == NULL) {
      dev->obj = new mbed::SPI(_mosi, _miso, _sck);
    }
}

void arduino::MbedSPI::end() {
    if (dev->obj != NULL) {                      //   <<<<<<<<<<  if dev == NULL this crashes.
        delete dev->obj;
    }
}
```

#### Proposal
```cpp
void arduino::MbedSPI::end() {
    if (dev != NULL) {
        if (dev->obj != NULL) {
            delete dev->obj;
        }
    }
}
```

**Comment by arotman** [comment]
This is an important bug fix, as the Arduino code dereferences a NULL pointer and just silently crashes. Ugly stuff. But easy to fix.
