### ISSUE TITLE
Can't Upload WiFi Firmware

### ISSUE THREAD

**Issue by alwint3r** [arduino/ArduinoCore-mbed#600]
I wanted to use the WiFi on a freshly opened Nicla Vision board, so I had to update the firmware first. But I encountered an issue where the WiFi partition couldn't be formatted. I used the 3.5.1 version from the board manager. I added a few check codes to check whether the format process results in an error or not, and here's the output:

```
root::init result: 0
No filesystem containing the WiFi firmware was found.
Usually that means that the WiFi firmware has not been installed yet or was overwritten with another firmware.

Formatting the filsystem to install the firmware and certificates...

Format result: -3101
Is fp null? 1
Flashing /wlan/4343WA1.BIN file
Flashed 0%
Writing
```

After an hour of pulling my long hair, I had to switch to my own setup (not using the Arduino IDE) which HEAD points to 933a3e143adb9d0dca13515800ad02261a7675eb commit. Then it worked.

**Comment by facchinm** [comment]
Hi @alwint3r , sorry for the inconvenience. I found the bug and pushed a fix (on mbed-os tree), it should be picked up in the next core release (likely in a few days).
When everything will be ok I'll close the issue properly.

Thanks

**Comment by alwint3r** [comment]
I updated the core version to 3.5.4, and I can confirm that I can write the WiFi firmware to the Nicla Vision board.

I'm closing this issue.

Thanks!
