### ISSUE TITLE
mbed not recognized in mbed-os-to-arduino script

### ISSUE THREAD

**Issue by MatthewMong** [arduino/ArduinoCore-mbed#603]
When running mbed-os-to-arduino I get an error on the lines where "mbed" is called saying mbed is not recognized. Is there a specific prerequisite that is required for this script to run?

**Comment by aqw42** [comment]
Hello Matthew

first you need to install mbedcli disponible here : https://os.mbed.com/docs/mbed-os/v6.15/build-tools/install-and-set-up.html
Using linux it is fairly easy to install but if you use windows follow this procedure : https://github.com/arduino/ArduinoCore-mbed/issues/570

Also you need to download patches folder
refer to this : https://github.com/arduino/ArduinoCore-mbed/issues/587
