### ISSUE TITLE
Wire.end() makes the rp2040 crash or hang somewhere, the reason being slave_th.terminate();

### ISSUE THREAD

**Issue by TheWorkshopByGM** [arduino/ArduinoCore-mbed#622]
I am trying to end the I2C to start a new one with a new address (for software addressing purposes). But every time I try to use Wire.end() it just hangs or crashes.

**Comment by facchinm** [comment]
Hi @TheWorkshopByGM ,
which core version are you using? The patch https://github.com/arduino/ArduinoCore-mbed/commit/b441a19058a3f3f0f157d21cef782e9f4cacbb09 is included in 3.5.4 and in fact doesn't set `slave` to `NULL` when calling `end()`, which could create issues if you switch role.
I'll post a PR soon to target the issue, if you could test it it would be great
