### ISSUE TITLE
Can't set static IP on GIGA R1

### ISSUE THREAD

**Issue by alranel** [arduino/ArduinoCore-mbed#643]
As reported in this forum thread: https://forum.arduino.cc/t/cannot-set-static-ip-on-giga-r1-wifi/1099937

This code seems to be ignored as IP gets still assigned by the router:

```
WiFi.config(IPAddress(192, 168, 0, 101), IPAddress(8, 8, 8, 8), IPAddress(192, 168, 0, 1), IPAddress(255, 255, 255, 0));
```

**Comment by facchinm** [comment]
Fixed by merging https://github.com/arduino-libraries/Ethernet/commit/72462ca2661ef5667fb2482a0b2c48b278c5333f and releasing Ethernet library v2.0.2
