### ISSUE TITLE
Usage of I2C and Serial port

### ISSUE THREAD

**Issue by lu7did** [arduino/ArduinoCore-mbed#677]
Hi,

Trying to port a firmware written for the Arduino core by Earle Philtower into mBed.

I do need to use a serial port at UART0 pins 16,16 (GPIO12/13) and a I2C device connected with pin 21,22 (GPIO 16/17), 
currently I'm defining the first with 

For the I2C

Wire.setSDA(16);
Wire.setSCL(17);
Wire.begin();

For the serial

 Serial1.setTX(12);
 Serial1.setRX(13);
 Serial1.begin(115200);

Would ask for a hint on how to do this in the mbed core.

Is there a documentation on the core somewhere?

Thanks in advance, Pedro.

**Comment by facchinm** [comment]
Hi Pedro,
in this core you can get the same result by using
```

**Comment by lu7did** [comment]
Thank you very much, appreciate!
