### ISSUE TITLE
Can't find Nano 33 BLE Sense board

### ISSUE THREAD

**Issue by va1labh** [arduino/ArduinoCore-mbed#679]
The Mbed OS Nano for some reason isn't showing the Nano 33 BLE Sense as target boards!

**Comment by facchinm** [comment]
HI @va1labh , which IDE are you using? `Nano 33 BLE` target is also intended for the `Sense` variant, so if you can see that entry everything is ok.

**Comment by va1labh** [comment]
I'm using Arduino IDE. I am able to program using Arduino nano BLE as the target. Thanks
