### ISSUE TITLE
How to configure QSPI for arduino ble 33 ?

### ISSUE THREAD

**Issue by haiga0203** [arduino/ArduinoCore-mbed#686]
I'm using QSPI to at a USB mass store like for example PluggableUSBMSD.h. But me when I configure and run the sample code it gives an error
I hope to get help. Thank you very much?

`In file included from C:\Users\nguye\Desktop\board_nrf\test1\test\test.ino:3:0:
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:266:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_send_program_command(mbed::qspi_inst_t prog_instruction, const void *buffer,
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:270:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_send_read_command(mbed::qspi_inst_t read_instruction, void *buffer, mbed::bd_addr_t addr, mbed::bd_size_t size);
     ^~~~~~~~~~~~~
     osStatus_t
In file included from C:\Users\nguye\Desktop\board_nrf\test1\test\test.ino:3:0:
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:273:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_send_erase_command(mbed::qspi_inst_t erase_instruction, mbed::bd_addr_t addr, mbed::bd_size_t size);
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:276:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_send_general_command(mbed::qspi_inst_t instruction_int, mbed::bd_addr_t addr, const char *tx_buffer,
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:285:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_read_status_registers(uint8_t *reg_buffer);
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:288:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_write_status_registers(uint8_t *reg_buffer);
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:291:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_set_frequency(int freq);
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:294:5: error: 'qspi_status_t' does not name a type; did you mean 'osStatus_t'?
     qspi_status_t _qspi_update_4byte_ext_addr_reg(mbed::bd_addr_t addr);
     ^~~~~~~~~~~~~
     osStatus_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:345:11: error: 'QSPI' in namespace 'mbed' does not name a type
     mbed::QSPI _qspi;
           ^~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:363:11: error: 'qspi_inst_t' in namespace 'mbed' does not name a type
     mbed::qspi_inst_t _read_instruction;
           ^~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:367:11: error: 'qspi_inst_t' in namespace 'mbed' does not name a type
     mbed::qspi_inst_t _write_status_reg_2_inst;
           ^~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:368:11: error: 'qspi_inst_t' in namespace 'mbed' does not name a type
     mbed::qspi_inst_t _read_status_reg_2_inst; // If three registers, this instruction reads the latter two
           ^~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:373:11: error: 'qspi_inst_t' in namespace 'mbed' does not name a type
     mbed::qspi_inst_t _4byte_msb_reg_write_inst;
           ^~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:396:5: error: 'qspi_bus_width_t' does not name a type
     qspi_bus_width_t _inst_width; //Bus width for Instruction phase
     ^~~~~~~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:397:5: error: 'qspi_bus_width_t' does not name a type
     qspi_bus_width_t _address_width; //Bus width for Address phase
     ^~~~~~~~~~~~~~~~
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:398:5: error: 'qspi_address_size_t' does not name a type; did you mean 'nrf_twi_address_set'?
     qspi_address_size_t _address_size; //Number of bits for address
     ^~~~~~~~~~~~~~~~~~~
     nrf_twi_address_set
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:399:5: error: 'qspi_alt_size_t' does not name a type; did you mean 'pin_size_t'?
     qspi_alt_size_t _alt_size; //Number of bits for alt
     ^~~~~~~~~~~~~~~
     pin_size_t
c:\Users\nguye\Documents\Arduino\libraries\libraries\qspif-blockdevice-master/QSPIFBlockDevice.h:402:5: error: 'qspi_bus_width_t' does not name a type
     qspi_bus_width_t _data_width; //Bus width for Data phase
     ^~~~~~~~~~~~~~~~`

**Comment by facchinm** [comment]
Hi @haiga0203 ,
some mbed functionalities are not compiled in the build used by the core; you can enable them though by following these instructions https://github.com/arduino/ArduinoCore-mbed#customizing-mbed-os-build-without-modifying-the-code and then the build will work.
