### ISSUE TITLE
Portenta_Video/Arduino_H7_Video not found in last release

### ISSUE THREAD

**Issue by dmazzella** [arduino/ArduinoCore-mbed#706]
Greetings,
just updated to version 4.0.4 but I can't find the `Arduino_H7_Video` library, I saw the rename from `Portenta_Video`, but without it I have problems with the build, for the moment I solved it by cloning the repository and copying the `Arduino_H7_Video` folder under my `libraries`.

Is there a release planned to integrate them?

thanks, 
D.

**Comment by facchinm** [comment]
Hi @dmazzella ,
there was a bug in the release process and the H7_Video library was not correctly packaged :disappointed: 
The fix has already been merged as https://github.com/arduino/ArduinoCore-mbed/commit/24138cc4b958d633ccb813d85fa1bab8a29f9693 ; in the meantime you can grab the folder from https://github.com/arduino/ArduinoCore-mbed/tree/main/libraries/Arduino_H7_Video (it should be  standalone) and just copy it in your sketchbook.
