### ISSUE TITLE
Giga CAN-bus CAN0 pins in pins_arduino.h do not match pin-out diagram or schematic

### ISSUE THREAD

**Issue by Gerriko** [arduino/ArduinoCore-mbed#727]
In pins_arduino.h we have:

```
#define CAN_HOWMANY       2

#define PIN_CAN0_TX       (PB_13)
#define PIN_CAN0_RX       (PB_12)

#define PIN_CAN1_TX       (PH_13)
#define PIN_CAN1_RX       (PB_8)

```

Schematic (FD_CAN2) and pin-out diagram show:
CAN_RX = PB_5
CAN_TX = PB_13

FD_CAN1 pins matches PIN_CAN1 RX/TX

**Comment by facchinm** [comment]
@Gerriko Thanks for reporting! Would you mind submitting a PR so we can give the proper attribution?

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino/ArduinoCore-mbed/pull/731
