### ISSUE TITLE
SocketWrapper library: `MbedClient.setTimeout` shadows `Stream.setTimeout`

### ISSUE THREAD

**Issue by JAndrassy** [arduino/ArduinoCore-mbed#728]
`MbedClient` has `setTimeout` instead of `setConnectionTimeout`. `setTimeout` shadows `Stream.setTimeout`

**Comment by JAndrassy** [comment]
Meanwhile I tested this timeout and it does work for `connect`. It is not possible to do timeout on `connect` with Mbed

**Comment by pennam** [comment]
> Meanwhile I tested this timeout and it doesn't work for `connect`. It is not possible to do timeout on `connect` with Mbed.

I've not tested it, but i think this is the reason https://github.com/ARMmbed/mbed-os/issues/13056#issuecomment-644612630

> I would recommend to rename to function to SetSocketTimeout
Got it! Thanks!
