### ISSUE TITLE
Add password length check to Wifi.beginAP()

### ISSUE THREAD

**Issue by megacct** [arduino/ArduinoCore-mbed#811]
Supplying a password of length < 8 currently crashes GIGA R1 with:

whd_wifi_init_ap() ERROR: 33555478
++ MbedOS Error Info ++
Error Status: 0x80010134 Code: 308 Module: 1
Error Message: Semaphore: 0x0, Parameter error
Location: 0x8050BF3
Error Value: 0x0
Current Thread: WHD Id: 0x24017868 Entry: 0x80570ED StackSize: 0x1400 StackMem: 0x240178B0 SP: 0x2407FEF4 
For more info, visit: https://mbed.com/s/error?error=0x80010134&osver=61700&core=0x411FC271&comp=2&ver=90200&tgt=GIGA
-- MbedOS Error Info --

**Comment by Rocketct** [comment]
ciao this should be fixed by https://github.com/arduino/ArduinoCore-mbed/pull/826
