### ISSUE TITLE
tone support no greater than 500Hz pitch

### ISSUE THREAD

**Issue by lzq420241** [arduino/ArduinoCore-mbed#84]
https://github.com/arduino/ArduinoCore-mbed/blob/b0a3c08cd873a6e99fa48ca90eebd22c76023210/cores/arduino/Tone.cpp#L27

**Comment by lzq420241** [comment]
better change 500ms to 500000us to support a higher pitch

**Comment by facchinm** [comment]
Hi @lzq420241 ,
thanks for reporting, I thought `std::chrono` to be a bit smarter and apply the right operation (I was wrong :slightly_smiling_face: ).
Will fix in a minute!
