### ISSUE TITLE
OPTA Ethernet.linkStatus() not returning LinkON

### ISSUE THREAD

**Issue by Goliath86** [arduino/ArduinoCore-mbed#844]
Hi, I'm having problem to use the Ethernet.linkStatus() function to check if the ethernet cable is connected or not. The function always return LinkOFF even on the Arduino OPTA LinkStatus example. Does the OPTA support this function?

**Comment by JAndrassy** [comment]
do you have some test sketch?

**Comment by Goliath86** [comment]
Event the nasic OPTA LinkStatus examlpe:
`
/*
  Link Status
  This sketch prints the ethernet link status. When the
  ethernet cable is connected the link status should go to "ON".
  NOTE: Only WizNet W5200 and W5500 are capable of reporting
  the link status. W5100 will report "Unknown".
  Hardware:
   - Ethernet shield or equivalent board/shield with WizNet 5200/5500
  Written by Cristian Maglie
  This example is public domain.
*/

#include <SPI.h>
#include <PortentaEthernet.h>
#include <Ethernet.h>

void setup() {
  Serial.begin(9600);
}

void loop() {
  auto link = Ethernet.linkStatus();
  Serial.print("Link status: ");
  switch (link) {
    case Unknown:
      Serial.println("Unknown");
      break;
    case LinkON:
      Serial.println("ON");
      break;
    case LinkOFF:
      Serial.println("OFF");
      break;
  }
  delay(1000);
}
`

**Comment by Goliath86** [comment]
So the example is not working "out of the box". I will try after the Ethernet.begin() function and I will post here the result. Thanks for the help

**Comment by JAndrassy** [comment]
the example is copied from the Ethernet library but there too `linkStatus` will work only after `begin`
