### ISSUE TITLE
ChatServer.ino not working

### ISSUE THREAD

**Issue by i-herrera** [arduino/ArduinoCore-mbed#852]
![image](https://github.com/arduino/ArduinoCore-mbed/assets/57756811/86c645b3-a0a4-4c9a-a51b-0d9e0b07797d)

ChatServer.ino example under the Ethernet library on the Examples for Portenta H7. When loading the sketch to the board the telnet command won't connect or freez after the connection. 

Core version: 4.1.1

**Comment by facchinm** [comment]
Due to `Server.available()` modernization ,this example might be removed in https://github.com/arduino/ArduinoCore-mbed/pull/793 (and replaced with the compliant AdvancedChatServer example)

**Comment by pennam** [comment]
closing the issue because #793 has been merged
