### ISSUE TITLE
mbed-os-to-arduino with MacOS

### ISSUE THREAD

**Issue by sabas1080** [arduino/ArduinoCore-mbed#87]
Hi

I am trying to compile my own variant, but when executing the command:

`./mbed-os-to-arduino -r /Users/xxxx/Documents/xxxx/mbed-os BASTBLE:BASTBLE`

I get the following error

```
./mbed-os-to-arduino: line 273: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by facchinm** [comment]
Hi @sabas1080 ,
trying to make the script correct for osx is a bit of a nightmare. One of the open PRs here https://github.com/arduino/ArduinoCore-nRF528x-mbedos/pulls could firx your problem but it's not a long term solution (and OSX support of unix utilities changes every release).
We are currently rewriting it in python for full cross platform compatibility :slightly_smiling_face: 
In the meantime I'd say that Linux is the only compatible platform
