### ISSUE TITLE
Missing WiFiClass::setHostname definition

### ISSUE THREAD

**Issue by dansiviter** [arduino/ArduinoCore-mbed#881]
The value is defined in the [header file](//github.com/arduino/ArduinoCore-mbed/blob/main/libraries/WiFi/src/WiFi.h#L93), but it has no definition resulting in:

```
undefined reference to `arduino::WiFiClass::setHostname(char const*)'
```

Related: #863

**Comment by Channel59** [comment]
This can be implemented rather easily if the patches in https://github.com/arduino/ArduinoCore-mbed/pull/921 are applied, similarly how it is done for the Ethernet class.
