### ISSUE TITLE
Ethernet defines SSID_MAX_LENGTH

### ISSUE THREAD

**Issue by ddmesh** [arduino/ArduinoCore-mbed#888]
https://github.com/arduino/ArduinoCore-mbed/blob/dd5abb6171063b2777620b9339510c63b915ce72/libraries/Ethernet/src/Ethernet.cpp#L3C9-L3C24

Question: why is this defined here and never used? should be removed

**Comment by pennam** [comment]
Fixed by https://github.com/arduino/ArduinoCore-mbed/pull/901
