### ISSUE TITLE
I2C frequency and waveform on Portenta H7

### ISSUE THREAD

**Issue by rchard-84** [arduino/ArduinoCore-mbed#89]
Frequency:
Wire.begin() should default to 100kHz clock for the I2C bus.  In the default appears to give 116kHz.  Wire.setClock(400kHz) gives 333kHz. 

Waveform:
The waveform for the SCL line is not normal.  It stays low for <2 mu seconds and then goes high.  If frequency was the only problem you'd expect 4.3 mus (half of the period).  This may be evidence it's a code issue and not a bungled circuit.

Attached are 2 pics showing scope traces of the SCL (yellow trace) and SDA( red trace).  The same code running on UNO (first pic) and another of it running on the Portenta (second pic).  UNO is right on frequency and has that nice clock signal shape.

On The UNO
![I2C_UNO](https://user-images.githubusercontent.com/58871972/99208444-68155580-278e-11eb-9f16-ecb6d2ad2a03.jpg)

On The Portenta
![I2C_PortentaH7](https://user-images.githubusercontent.com/58871972/99208450-6cda0980-278e-11eb-9ff3-940a8a8779d7.jpg)

Some I2C devices did successfully receive data from the Portenta on the I2C Bus however I couldn't get several sensors to send data back.  The same sensors have no issue on the UNO.  My sensor connectivity challenge could be related to the waveform issue, I don't know.

**Comment by facchinm** [comment]
Hi @rchard-84 ,
you are very right. I2C "waveform" calculation on STM32 mbed implementation is very rough (https://github.com/ARMmbed/mbed-os/blob/master/targets/TARGET_STM/TARGET_STM32H7/i2c_device.h#L38) and very wrong if APB1CLK is not 54Mhz . We are preparing a patch for fixing it and make I2C compliant again.
Will let you know as soon as it lands on something stable so you can test it.

**Comment by facchinm** [comment]
Will be fixed by https://github.com/ARMmbed/mbed-os/pull/14030
