### ISSUE TITLE
vsnprintf with length of 80 chars for format hardfaults the board

### ISSUE THREAD

**Issue by janjongboom** [arduino/ArduinoCore-mbed#92]
This sketch hardfaults the board on v1.3.0 of this Arduino Core on the Arduino Nano 33 BLE Sense:

```
void printf_wrapper(const char *format, ...) {
    static char print_buf[2048] = { 0 };

    va_list args;
    va_start(args, format);
    int r = vsnprintf(print_buf, 2048, format, args);
    va_end(args);

    if (r > 0) {
        Serial.write(print_buf);
    }
}

void setup() {
  // put your setup code here, to run once:
  delay(5000);
}

void loop() {
  // put your main code here, to run repeatedly:

  printf_wrapper("hello world\n");
  printf_wrapper("hello this is a long text with 40 chars\n");
  printf_wrapper("hello this is a long text with 80 chars hello this is a long text with 80 chars\n");

  delay(1000);

}
```

This works fine on the 1.1.6 core.

**Comment by facchinm** [comment]
Hi Jan,
it looks like https://github.com/arduino/ArduinoCore-mbed/pull/88 already fixes the issue so it may be an mbed problem.
Would you mind testing it?

**Comment by janjongboom** [comment]
@facchinm OK, good to know - we're patching our sketches for now. When do you expect a new core version to come out for this?

**Comment by facchinm** [comment]
Just waiting for this PR to be merged https://github.com/ARMmbed/mbed-os/pull/13826 :wink:

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino/ArduinoCore-mbed/commit/6c36b4252e7d56c03c112ea5549a39eb90ed5de5
