### ISSUE TITLE
Compile libmbed.a in Ubuntu error

### ISSUE THREAD

**Issue by sabas1080** [arduino/ArduinoCore-mbed#95]
Hi

Im trying compile libmbed.a in ubuntu but I have the next error

![Captura de pantalla de 2020-12-07 19-31-06](https://user-images.githubusercontent.com/2874292/101426879-6a695c00-38c3-11eb-866c-47edba280d34.png )

I can't found the file link_option, thanks

**Comment by facchinm** [comment]
@sabas1080 to get the real error message you can navigate to `/tmp/mbed-os-program` and launch `mbed compile`.
This will show why the compilation is failing (and thus "final" files are not generated)
